name: C/C++ CI

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "haroldstx"
        git config --global user.email "haroldhdiaz@gmail.com"

    - name: Set up C++ compiler
      run: sudo apt-get install -y g++

    - name: Compile main.cpp
      run: g++ -o main main.cpp

    - name: Create input file
      run: echo "Esta es una prueba. Busca la palabra 'lluvia' en este archivo de texto." > Archivo.txt

    - name: Run the program
      run: ./main
