name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: lukka/get-cmake@v3.21.3
      with:
        cmake-version: '3.21.3'
      
    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Build the code
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run linting
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --inconclusive --std=c++11 .

    - name: Run unit tests
      run: |
        cd build
        ctest

    - name: Audit dependencies
      run: |
        sudo apt-get install -y ldd
        ldd ./your_executable_name

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: lukka/get-cmake@v3.21.3
      with:
        cmake-version: '3.21.3'
      
    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Build the code
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Deploy to production server
      env:
        PROD_SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
        PROD_SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}
        PROD_SERVER_KEY: ${{ secrets.PROD_SERVER_KEY }}
        DEPLOY_PATH: /.github/workflows
      run: |
        echo "${{ secrets.PROD_SERVER_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no ./build/your_executable_name ${{ env.PROD_SERVER_USER }}@${{ env.PROD_SERVER_HOST }}:${{ env.DEPLOY_PATH }}

    - name: Run smoke tests
      env:
        PROD_SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
        PROD_SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}
        DEPLOY_PATH: /.github/workflows
      run: ssh -o StrictHostKeyChecking=no ${{ env.PROD_SERVER_USER }}@${{ env.PROD_SERVER_HOST }} "cd ${{ env.DEPLOY_PATH }} && ./run_smoke_tests.sh"

